spring.application.name=demo
# Database Configuration

#localhost
# spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot
# spring.datasource.username=postgres
# spring.datasource.password=newpassword

# Supabase
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.mkueqypruqbxalkzloqs
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


